config/routes.rb
Rails.application.routes.draw do
  resources :authors do
    resources :books
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    Author.create(get_author_params)
    redirect_to authors_path
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    author = Author.find(params[:id])
    author.update(get_author_params)
    redirect_to authors_path
  end

  def destroy
    author = Author.find(params[:id])
    author.destroy
    redirect_to authors_path
  end

  private
  def get_author_params
    params.require(:author).permit(:name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @author = Author.find(params[:author_id])
  end
  def show
    @author = Author.find(params[:author_id])
    @book = Book.find(params[:id])
  end
  def edit
    @author = Author.find(params[:author_id])
    @book = Book.find(params[:id])
  end
  def update
    author = Author.find(params[:author_id])
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to author_books_path(author)
  end

  private
  def book_params
    params.require(:book).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<%= form_for @author do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Submit" %>
<% end %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<ul>
  <% @authors.each do |writer| %>
  <li><%= link_to writer.name, writer %></li>
  <% end %>
</ul>

<%= link_to "add new author", new_author_path %>

app/views/authors/new.html.erb
<h1>Add new author</h1>

<%= form_for @author do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Submit" %>
<% end %>

app/views/authors/show.html.erb
<h1>Show Author</h1>

<p>Name: <%= @author.name %></p>

<!-- LINK TO BOOKS -->
<%= link_to "ALL BOOKS", author_books_path(@author) %>
<br><br>
<!-- END LINK TO BOOKS -->

<%= link_to "edit", edit_author_path(@author) %>
|
<%= link_to "delete", @author, :method => :delete %>

<br>

<%= link_to "back to all authors", authors_path %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= form_for [@author, @book] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit "Submit" %>
<% end %>

app/views/books/index.html.erb
<h1><%= @author.name %></h1>

<ul>
  <% @author.books.each do |novel| %>
  <li><%= link_to novel.title, author_book_path(@author, novel) %></li>
  <% end %>
</ul>

app/views/books/new.html.erb
<h1>books#new</h1>
<p>find me in views/books/new.html.erb</p>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p>By: <%= @author.name %></p>

<%= link_to "edit", edit_author_book_path(@author, @book) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthorExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>